name: GitHub To Tencent 

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git init
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git fetch --all
          for branch in `git branch -a | grep remotes | grep -v HEAD`; do
            git branch --track ${branch##*/} $branch
          done
        env:
          GITHUB_REPOSITORY: Tencent/CodeAnalysis

      - name: Push to Tencent
        run: |
          remote_repo="https://${TENCENT_USERNAME}:${TENCENT_PASSWORD}@git.code.tencent.com/${TENCENT_REPOSITORY}.git"
          git remote add tencent "${remote_repo}"
          git show-ref # debug
          git branch --verbose
          # publish all
          git push --all --force tencent
          git push --tags --force tencent
        env:
          TENCENT_REPOSITORY: Tencent_Open_Source/CodeAnalysis
          TENCENT_USERNAME: ${{ secrets.USERNAME }}
          TENCENT_PASSWORD: ${{ secrets.PASSWORD }}
